apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: libreserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/libreserve/libreserve-web-reserver:dev
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "https://dev-coe.ionize13.com/api"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: libreserve
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000