version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: coe_workshop_db
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  postgres_data:
